/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookCard: typeof import('./src/components/HomeComp/BookCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavi: typeof import('./src/components/HomeComp/TopNavi.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    WaterFall: typeof import('./src/components/HomeComp/WaterFall.vue')['default']
  }
}
